# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- staging

pool:
  name: Default  # Replace with the name of your self-hosted agent pool

jobs:
- job: CopyFilesJob
  displayName: 'Copy Files and Create Artifact'
  steps:
  - checkout: self
  - task: CopyFiles@2
    displayName: 'Copy Files'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/my-bucket'
  - task: ArchiveFiles@2
    displayName: 'Create Artifact'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/my-bucket'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/my-bucket.zip'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

